name: 'BLOGAutoUpdate'

on:
  push:
  schedule:
    - cron: '0 1 * * *'

jobs:
  stale:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          # in this example, there is a newer version already installed, 3.7.7, so the older version will be downloaded
          python-version: ['3.7.4']
      steps:
      - uses: actions/checkout@v2 # Checking out the repo
      - name: Install dependecies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d # Install all dependencies, including development ones
      - name: Build
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run build
      - name: Commit and push if changed   # 更新README.md
        run: |
          git diff
          git config --global user.email "1183503933@qq.com"
          git config --global user.name "leonyan"
          git add README.md
          git commit -m "Github Action Auto Updated"
          git push
